node:
  cluster: cluster-1
  id: envoy-instance-1
dynamic_resources:
  lds_config:
    path: /etc/envoy-lds.yaml
  cds_config:
    path: /etc/envoy-cds.yaml
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001
  access_log:
  - name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog